### ISSUE TITLE
Allow hostnames with dots

### ISSUE THREAD

**Issue by jabl** [chaos/genders#15]
Sometimes it might be useful to have hostnames with domain parts in the genders file (say, a naming convention like nodeN.rackM.someDomain). But currently nodeattr -k at least complains about that.

Would it be possible to allow that?

**Comment by BenCasses** [comment]
If you use the configure option --with-non-shortened-hostnames, you can bypass the parse check that complains about periods.  Your mileage may vary, however.  We don't use this feature because it isn't clear what the relationship between mixed long and short hostnames should be, for example: if "nodeK" and "nodeN.rackM.someDomain" both exist, does that imply that "nodeK"=="nodeK.rackM.someDomain"?

**Comment by chu11** [comment]
I thought I'd throw out another example, if "nodeK.rackM.someDomain" is your local hostname (returned by hostname command), should that map to "nodeK" or "nodeK.rackM.someDomain" in the Genders file?

**Comment by jabl** [comment]
Point taken. I suppose one would need to specify that nodenames should have the same number of dots. Or alternatively somehow figure out whether nodeK == nodeK.rackM.someDomain, e.g. by doing a DNS lookup of both the short and long names. But that's not good from a performance perspective, especially if you have lots of hosts.. (of course one could use an async DNS library and fire off all the queries ASAP, but still..).
