### ISSUE TITLE
make genders MUCH faster at parsing

### ISSUE THREAD

**Issue by stuartm-dugeo** [chaos/genders#24]
You may or may not want this... but its a patch we run to make genders MUCH faster at parsing the database.

As some background, we are using genders as the source of truth for lots of information about each node... so every node has its own entry and we have LOTS of atributes (mac addresses, ip, serial numbers etc).  The file is over 10MB in size.  Reading it 1 character a time was very very slow.  This patch makes it at least 10x faster.

[genders_fastparse.txt](https://github.com/chaos/genders/files/2292716/genders_fastparse.txt)

**Comment by stuartm-dugeo** [comment]
I see some activity in this project.  Any chance this patch can get pulled in?

**Comment by chu11** [comment]
I recall this issue popping up a long time ago.  Generally speaking patch idea looks fine.   Could you send a pull request for @BenCasses to look at.

**Comment by philregier** [comment]
Pending a merge, *IF* each node has its own entry then you should be able to dramatically speed up parsing with something like (in bash, at least, or via `bash -c`)

`nodeattr -f <(grep -w ^$node /etc/genders) <query>`

Pretty useless otherwise, and reading more than one character at a time is clearly the right thing to do anyway.  Thanks for putting in the request, @stuartm-dugeo .

**Comment by BenCasses** [comment]
This looks good.  Make a pull request and we'll get it in there.

**Comment by stuartm-dugeo** [comment]
This has made it into the main tree.  Closing.
