### ISSUE TITLE
Prefix[x-y] not working properly

### ISSUE THREAD

**Issue by otheus** [chaos/genders#5]
Just installed 1.22 packaged by Fedora, released May 20 2015.

`Prefix[x-y]` doesn't work while `Prefix[x-y]Suffix` does

```
me $ echo "db[1-3]   example" >/etc/genders
me $ nodeattr --parse-check
nodeattr: 0 parse errors discovered
me $ nodeattr -A
db[1-3]
me $ echo "db[1-3]-t test" >.genders
me $ nodeattr -A
db1-t,db2-t,db3-t

```

Same for `Prefix[a,b,c,...]`. Doesn't work without a suffix.

How is it possible no one has noticed this error before?

**Comment by BenCasses** [comment]
As far as we can tell, this works as intended.   If you want to force comma separated list rather than hostlist format, use -c:
```
me $ nodeattr -A
db[1-3]
me $ nodeattr -c -A
db1,db2,db3
```

**Comment by otheus** [comment]
Thanks for pointing out that it works as expected with `-c` (and `-n` and `-s`). But how can you say it works "as intended"? If that is the intention, it is poorly documented. Notice how expansion is performed with other hosts where a suffix exists. Also, notice that if `-q` is given, it prints out
```
db[1-3]
```

I will note that with `-Q`, the functionality _is_ as expected:
```
me $ nodeattr -Q db03 example ; echo $?
0
```

This variance is not indicated in either the `man` page nor the other documentation. I submit this is a bug.

**Comment by chu11** [comment]
Hi @otheus, I think there is a bit of confusion based on what is perceived as correct output.

In your original post, I think you were expecting comma separated to be the default output? The -q (hostrange) format is default.  So

```
me $ nodeattr -A
db[1-3]
```

Is correct.  I notice that we don't state the -q output is the default in the nodeattr manpage, so we should note that.

I think what was perhaps meant was "The output of Prefix[x-y] is inconsistent to Prefix[x-y]Suffix"???

In that case yes, that should be noted.  The documentation does not explicitly state that suffix support is supported, but it should perhaps be noted that it may only tangentially be supported.  This is due to the underlying implementation of the 'hostlist' library (which is used by other projects like pdsh, powerman, slurm, and others).  Unsure if this is something the hostlist author desires to fix or not, but I can ask him.

**Comment by chu11** [comment]
@BenCasses 

I think we need to update documentation in two areas.  In the nodeattr manpage, something indicating that -q/hostrange format is what is the default output.

In the TUTORIAL, we should add information on hostlist/hostrange format.  I think we can steal language from pdsh on format.
